import type { Metadata } from "next";

import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "WBPRO - Wildberries аналитика",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main>{children}</main>;
}
