export const API_URL = `${process.env.NEXT_PUBLIC_API_URL}`;

export const TOKEN =
  "ZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKSVV6STFOaUo5LmV5SnBaQ0k2TVN3aVkyOXRjR0Z1ZVY5cFpDSTZNU3dpY205c1pYTWlPbHNpWVdSdGFXNGlYU3dpY205c1pTSTZJbUZrYldsdUlpd2laWGh3SWpveE56SXhORGMwTWprMExqWTVNRFkyTm4wLlY0T1dqNFNraGIyYkFHeHR3eFdrRWdMODlfcE1zVW93NG9tMXFBa1l1OVk=";

export const APIs = {};
